name: Build and Release EZ-Theme

on:
  workflow_dispatch:   # 手动触发

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write   # 允许创建 Release 和上传文件

    steps:
      # 1. 拉取代码
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. 设置 Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # 3. 安装依赖
      - name: Install dependencies
        run: |
          npm install
          npm install defu --save
          npm install --legacy-peer-deps

      # 4. 构建项目
      - name: Build project
        run: npm run build

      # 5. 压缩 dist
      - name: Zip dist
        run: zip -r ez-theme-dist.zip dist

      # 6. 创建 Release 并上传文件
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: build-${{ github.run_number }}
          name: "Build ${{ github.run_number }} (${{ github.sha }})"
          body: "自动构建的 EZ-Theme 打包文件"
          draft: false
          prerelease: false
          files: ez-theme-dist.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
