name: Build and Release EZ-Theme

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write   # 允许创建 Release 和上传资产

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: |
          npm install
          npm install defu --save
          npm install --legacy-peer-deps

      - name: Build project
        run: npm run build

      - name: Zip dist folder
        run: zip -r ez-theme-dist.zip dist

      - name: Create or update Release via softprops
        uses: softprops/action-gh-release@v2
        with:
          tag_name: build-${{ github.run_number }}
          name: "Build ${{ github.run_number }} (${{ github.sha }})"
          body: "Automatically built artifact"
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload asset to that Release
        uses: softprops/action-gh-release@v2
        with:
          files: ez-theme-dist.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
